version: '3'

services:
  ms-usuario-app: # Renomeado para ms-usuario-app
    image: openjdk:latest
    container_name: ms-usuario-app # Renomeado
    working_dir: /app
    volumes:
      - ./target:/app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ms-usuario-db:3306/ms_usuario?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo # Corrigido o nome do serviço
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - ms-usuario-db # Renomeado
    command: ["java", "-jar", "/app/parquimetro-app.jar"]

  ms-usuario-db: # Renomeado para ms-usuario-db
    image: mysql:8
    container_name: ms-usuario-db # Renomeado
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=grupo44
    ports:
      - "3306:3306"
